name: Build

permissions:
  contents: write

on:
    push:
        tags:
          - '*'

jobs:
    release:
        name: build and release electron app dog-clock
        runs-on: ${{ matrix.os }}
        
        strategy:
            fail-fast: false
            matrix:
              os: [windows-latest, macos-latest]
                
        steps:
            - name: Check out git repository
              uses: actions/checkout@v2
            
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "20"
                
            - name: Install Dependencies
              run: npm install
            
            - name: Build Electron App
              run: |
                npm run build
                echo "GitHub Ref: ${{ github.ref }}"
            
            - name: Cleanup Artifacts for Windows
              if: matrix.os == 'windows-latest'
              run: |
                npx rimraf "dist/!(*.exe)"
            
            - name: Cleanup Artifacts for MacOS
              if: matrix.os == 'macos-latest'
              run: |
                npx rimraf "dist/!(*.dmg)"
                
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.os }}
                path: dist
                
            - name: release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: "dist/**"